### ISSUE TITLE
Is it easy to overload the server?

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#117]
Dear François,

I ask myself 2 questions related to the server overload in the context I use tableaunoir:
1. Since this month I sometimes use a shared board (with **no privilege** access for others) during sessions with a hundred of students... Do you think I should not use tableaunoir in this context until the server will be upgraded?
2. Moreover, and although without writing privilege, I have noticed that some students have fun constantly moving their mouse (e.g. by infinitely drawing the infinity symbol)... Do you think this could have any effect on server overload?

**Comment by francoisschwarzentruber** [comment]
Dear philardine,

thank you for your two relevant questions. 
1. The server will be upgraded tonight I think. :) The Ctrl+Z bug (#113) is unrelated to the server efficiency. But the loading time is, I think. Sometimes, I wait 20 seconds to reach a board! (it depends on the content of the board)
2. Drawing or moving the mouse does send a lot of small messages. Normally that is ok. But you suggest a very naïve improvement: if there is no drawing into play, tableaunoir should send less messages! The precision of other mouse pointers will be less precise, but I think we do not care if there is no drawing. I will think about it.

**Comment by philardine** [comment]
Dear François,
I agree with you. Naïve improvements are beautiful, just as simplicity is beautiful :-)

**Comment by francoisschwarzentruber** [comment]
:) With the "naïve improvement", there are less msg sent (before, every captured mousemove event was sent!, now: the duration must be 100ms at least (making 25% msgs sent only), except if the user is drawing, then it is as usual). It means that:
- normally, tableaunoir may be more reactive to what you are drawing (I am not sure of that)
- the other cursor movements are updated jerkily.

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

I experienced disconnection today, but without loss of data (since now, the data are also stored locally).I just pressed F5 and I was connected again.

Maybe, it is caused by server overloads but I am not sure. Now the direction of improvement could be inspired from what it is done in video games. Some of the features are difficult to implement, I just list them to let you know:
- a reconnection procedure (no need to press F5 anymore)
- peer-to-peer connection via WebRT
- share the "responsability" of some part of the board. For instance, the data for magnet 1 will be hold and transmitted if needed by user 43 whil the magnet 2 will be hold by user 86 etc. (currently the user with the smallest ID has the responsability of the full board!)

**Comment by philardine** [comment]
Dear François,

This is good news! Thank you :-)

FYI I still get  #113 bug from time to time, but I no longer lose data.
Last time (last week... can't remind when exactly) F5 was not enough to connect me again. I created a new instance before reloading the previously saved tableaunoir and it did the job.

Good luck for the new improvements you're planning!
Cheers

**Comment by francoisschwarzentruber** [comment]
I think the server is not overloaded. We will soon improve the performance of the reconnection procedure (issue #145). The reconnection will be faster.
