### ISSUE TITLE
`c` key should cycle through colors

### ISSUE THREAD

**Issue by rzach** [tableaunoir/tableaunoir#120]
Currently pressing `c` cycles to the next color and opens the color picker. But then pressing `c` again doesn't do anything.

I would suggest to let `c` either cycle through the colors. Personally I'd prefer this happens without the color picker being opened (would be less distracting; also hard to see where you want to draw if the picker is open).

**Comment by francoisschwarzentruber** [comment]
Dear Richard,
thank you for your nice suggestion. I understand that the color menu can be annoying. Now, there is an option to prevent that menu to appear if you do not want it to appear when you use the keyboard.
I preferred it to be an option because sometimes I get lost in the color ordering. Actually, in the very very first version of tableaunoir, there were only 3 colors: white, blue and orange, so it was difficult to forget the color ordering. What do you think? Would you like to have only three colors in the palette?

**Comment by rzach** [comment]
No, I think the number of colors is nice (and the colors themselves). But maybe making the palette configurable (add, delete colors, select colors with a color picker) could be something for the future.  You'd somehow need to make it persistent for the user though.

The option is good. You might have it unchecked as the default? Also there should be a `<br>` after it so the palette options line up.

**Comment by rzach** [comment]
Tested the option, thank you. I now realize that the reason it doesn't cycle is because Firefox traps the cursor in the searhc box, so subsequent tableaunoir doesn't see my subsequent `c` keypresses. See issue #122

**Comment by francoisschwarzentruber** [comment]
Thank you for your messages. I prefer to keep checked by default for the moment. Note that options are persistent. If you quit, or even quit the browser, the options are still there (localStorage).
I will see issue #122.
PS: The palette editor will come later ;)
