### ISSUE TITLE
Is there a way to hide the "history" bar at the bottom, as it is the case for the tool bar at the top ?

### ISSUE THREAD

**Issue by FrPellegrini** [tableaunoir/tableaunoir#143]
Everything is in the title.  :-)

**Comment by francoisschwarzentruber** [comment]
Yes! In the toolbar at the top, click on the button "Animation".
But, your question tells that there should be a closing button in the history bar.

**Comment by FrPellegrini** [comment]
More efficiently, a keyboar shortcut (like the "h" for the tool bar), to mimimize the number of actions to perform. Clicking on the top to have the history bar disappear means that you have to make it appear, and then remove the history bar. This is two actions. Too long.  :-)

**Comment by francoisschwarzentruber** [comment]
What about:
- using "a" to toogle the animation bar?
- and also adding a close button on the animation bar?

**Comment by francoisschwarzentruber** [comment]
"a" to toggle the animation bar is implemented. Finally, I think that adding a close button is not needed because:
- if the toolbar is still here, the user just clicks again the button "Animation" again
- if the toolbar is not here, the user has removed it and is assumed to know and use the keyboard shortcut
What do you think?
