### ISSUE TITLE
print(rubber stamping) for text magnets doesn't work

### ISSUE THREAD

**Issue by tubaman** [tableaunoir/tableaunoir#148]
I was surprised that when I try to print/copy/rubber stamp a text magnet, it doesn't work.  I intuitively expected that if I try to rubber stamp a text magnet, I'd be able to.  Here's a screen capture of what I tried: https://youtu.be/W4BEiyg4iOI

**Comment by francoisschwarzentruber** [comment]
Point 2 is solved (well, maybe the order of stamping could be improved though).

Point 1 is partially solved. The issue is that html2canvas does not work properly. Sometimes it raises the error 
                 `Unable to find element in cloned iframe
So now, for text magnet it works, but for single line text magnet. Multiple line could be easily implemented... but stamping a LaTEX MathJAX element is tricky. It does not work properly with html2canvas.

A solution would be to test another library for blitting DOM elements. What do you think?

**Comment by francoisschwarzentruber** [comment]
Dear Ryan,
I hope you are fine. Do you still have troubles in printing magnets? The current version is not perfect but is maybe sufficient for what people need. What do you think?

**Comment by tubaman** [comment]
Yup, works much better for me now.  Thanks!
