### ISSUE TITLE
Ctrl+C leaves maget's contour behind

### ISSUE THREAD

**Issue by osankur** [tableaunoir/tableaunoir#196]
When creating a magnet with ctrl+C the expected behavior is that this does not change the underlying image. However, a black contour is left behind.

**Comment by francoisschwarzentruber** [comment]
The issue is normally solved on the branch "magnetize" (not "main"). I have to test it a bit. 

The issue was the contour was erased by simply drawing in transparent on top of it. It was tricky to solve that issue, because we have to cancel the drawing before transforming the zone into a magnet. Cancelling (removing the actions) is tricky because drawing is asynchronous because some actions may be asynchronous (like pasting a magnet since we have to wait and be sure that the magnet image is loaded). Well.

Many modifications of the code have been done to solve that.
- creation of an operation for magnetizing a portion of the board
- cleaning the code of the previous class called Delineation which was a mess. Actually, the code for magnetizing existed almost since the beginning of Tableaunoir. A time where actions, making presentations was impossible. So making an object Delineation to store the current path was kind of ok. Now, it is completely stupid and this code contained too many side effects, which leads to maintainability issues. Well... I simply destroy the class Delineation, and I wrote a class Magnetizer in a more functional programming style.

**Comment by francoisschwarzentruber** [comment]
Closed!
