### ISSUE TITLE
slide shift during export to .pdf

### ISSUE THREAD

**Issue by JoanThibault** [tableaunoir/tableaunoir#220]
First,
I'd like to thank you very much for this very usefull software :smile: 

When exporting to .pdf (very useful feature) I noticed that the slide are shifting at each page.
I created MVE using the "split the screen line" only :

[slide-shift.zip](https://github.com/tableaunoir/tableaunoir/files/8601778/slide-shift.zip)

[myblackboard.pdf](https://github.com/tableaunoir/tableaunoir/files/8601783/myblackboard.pdf)

**Comment by francoisschwarzentruber** [comment]
Dear JoanThibault,
thank you for having posted that issue. Indeed, this is an important problem. The thing is that the PDF export uses the size of the window for making the PDF pages. If you are at the leftmost part of the board, the first PDF page will contain exactly the content of your window. I find it convenient but even so, it is maybe a wrong design for the PDF export. 

The improvements of Tableaunoir maybe:
1- to inform more the user of the content of the PDF pages (maybe a preview?)
2- let him/her choose what will be the pages (complicated)

What do you think?

PS: there is actually another problem with that features: the export is... too slow. Due to the way Tableaunoir works (the eraser that works like a real one for instance), the easiest result is a bitmap image. So each PDF page is actually a bitmap. It could be vectorial but as said, it would a mess to handle the use of the eraser.

**Comment by francoisschwarzentruber** [comment]
### main issue
The length of the shift left/right is half of the window width! When Tableaunoir is fullscreen, then the window width = the screen width, and the board is shifted to the right/left by an half screen. The actual PDF export has a bug: I was unable to modify the dimension of the PDF pages. They seem to remain in A4 whereas I would have preferred the dimension to be the dimension of the board (the size of the window, i.e. the viewport). What do you think?

### performance issue
In its full generality, no because you can have a background etc. etc.
However, the common use is a *simple* board: uniform black/white background. So maybe an improvement could be:
a- if the board is complicated (complicated background), we keep the current naïve and slow procedure that generate bitmaps of the screenshot to create the PDF)
b- if the board is simple, use your trick: the eraser is just a line whose color is the background color! Thus, we can export in PDF as a vector objects. <== this should definitely be implemented. What do you think?

**Comment by JoanThibault** [comment]
# main issue
Indeed it looks like a bug, could you point me to piece of code that deals with pdf export, so that I know where to start :-)

A4 is not necessarily bad, but matching the size of the window would be better

# performances issue

## Uniform Background

I think it would be great :-) , It would reduce export-time and memory consumption, while improving quality when resizing :+1: 

## Non-Uniform Background

In the case of imported image, I don't think there is much to do, just like you suggest.

But in the case, of "wallpaper", I think one could describe each :-)

**Comment by francoisschwarzentruber** [comment]
Normally the export in PDF has been solved.
You can also find the documentation that has been recently updated: https://github.com/tableaunoir/documentation/blob/main/export.md

ps: the performance optimization has not been implemented
ps : the progress bar has to be implemented at some point :)

**Comment by JoanThibault** [comment]
Indeed the export in pdf has been solved :+1: :smile: 

However, I do not understand the sentence "There are two behaviors depending on your board is a classical one or a presentation with slides." when I do not see an option available in the 'export' view of tableaunoir ?

**Comment by JoanThibault** [comment]
I just noticed that contour have been "removed" as a side effect of the bug fix, it looks way better like this :-)

**Comment by francoisschwarzentruber** [comment]
I am happy that PDF export is working now! Thank you again for having reported that issue!

I agree: the sentence "There are two behaviors depending on your board is a classical one or a presentation with slides." is not clear. I expanded a bit the text in the documentation. Actually, there will be soon some illustrations to explain how the PDF export in the both cases.

By contour, you mean the "white" board that was surrounding the board on a PDF page? Yes, now, the size of a PDF page matches the window size.

**Comment by francoisschwarzentruber** [comment]
If you are happy, then I am happy too and I close this issue. (It can be reopened later on if needed).
