### ISSUE TITLE
Draw geometrical shapes

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#4]

**Comment by liar666** [comment]
Hi there,

Thanks a LOT for the app. I tried a serious amount of whiteboards on the web and could not find any that fits my needs (probably because mine are closer to yours: I'm a teacher in computer science too :) ), and particularly one that would not require to create an account or would not be FOSS.

However, I mainly teach Software Engineering and I need to draw UML diagrams. So a few common shapes (rectangle, ellipsis - & the little human character) and a few arrow types would be welcome :)

To exmplain further the need:
The idea is that during their normal face-to-face Labs my students are required to draw perfect UML diagram, following the description of a system. They work with tools like with http://www.umletino.com/umletino.html . The problem is that with the current situation (COVID) and virtual class, if I directly use such tools, I'll just give (& share) them the answer so they won't have anything to do. Thus I'm looking for is a tool to "simulate" an actual whiteboard, where I can draw very imperfect UML diagrams (&sometimes wrong on some aspects - e.g. wrong type of arrow, because I'm explaining something else in my current drawing) to show some particular aspect of a particular diagram without providing the final solution. 

PS: I've added you app to alternativesto, to give it more visibility :) https://alternativeto.net/software/tableaunoir/

**Comment by francoisschwarzentruber** [comment]
Thank you for your message. I am still thinking about how would these features be implemented. There are several solutions:
1. adding a button per shape (but the GUI will be heavy)
2. recognize drawn shapes (a bit annoying when shapes are recognized whereas they should not be)
3. playing with special kind of magnets that can be parametrized, and then "stamped" to draw the shape (the advantage is that it would be easy to redraw the same shape several times)
4. not implementing these features since, drawing an imprecise line, an imprecise ellipse/rectangle with a graphical tablet is easy

I have a preference for 3 since it fits to the spirit of tableaunoir, and fits to the need of drawing several times the same shape, or some part of the same shape.

This issue remains open. Do not hesitate to comment.

PS: thank you very much for having create the page about tableaunoir on alternativeto!

**Comment by Naereen** [comment]
I would vote for 4 and keep tableaunoir "simple" as it is.

**Comment by morandat** [comment]
1: depends on how button are showed. For instance, a palette (a la color palette) may be ok for basics shape (line, rectangle, ellipse, .... triangle, pentacle, octogon ...). However that do not really scale .... but maybe there are not so many shapes.
3: would allow UML and why not electronic & so on. Palette could also be a nice way of presenting magnets.
4: has the big advantage that it cost nothing

**Comment by philardine** [comment]
I would vote for 1.
When you use schema to explain abstract concepts, you ofently use geometrical shapes, at least square/rectangle and circle/ellipse.
The menu could offer just 2 buttons : ellipse and rectangle. Using Shift can permit the drawing of circle or square...

**Comment by francoisschwarzentruber** [comment]
Dear all,
thank you for your answers. I opted for 1. I keep 3 in mind (1 and 3 are not incompatible after all).
Maybe that is not perfect, but we can now draw geometrical shapes! 
Do not hesitate to open new precise issues, but I close this general issue.
Have a nice day!
