### ISSUE TITLE
Background image not visible for sharees

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#58]
Hi!
Today, sharing a blackboard with my students, I was the only one able to view the background image of the board (png file).
I dont think it is the intended behavior, isn't it ?
PS : And also, when I press F5 the background image is discarded, and I have to set it again (annoying).

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
I am sorry for the inconvenience. I completely forgot to share backgrounds. Now, it should work. Well it is not perfect yet...
- a student can change your background ;)
- it is maybe not completely stable
- the menu for choosing the background is a bit ugly
- maybe, choosing whiteboard and blackboard should be in the background menu, and not in the option menu? (the option menu is I think really intended to tune tableaunoir)
- maybe a discussion on the fact that the background should scroll or not (it does not now, so that for instance a teacher in geography may draw several information on the same map)
- maybe add the possibility to add several images? or a pdf document (slides)?
PS: F5 still discards everything. But for a shared board, as you become a new user, the background should be loaded again.

**Comment by philardine** [comment]
Great!
- students can change the background: ok, I can live with this, saying them not to do so is generally well understood ;-)
- stability: will try it in the morning
- menu ugly: can be enriched with next point (b/w background)
- black/white background configuration in the background submenu: I agree with you
- scrolling of background: and what do you think about letting users to define more vertical boards (as in the old good times, with multi vertical sliding board pieces), for example with up/down arrows?
- possibility to add multi-backgrounds: would be nice, would not break the actual interface simplicity (for the final user :-D)

And I want to add another demand. I know you already talked about this, but the toolbar place (horizontal up) is annoying when you load a background image. Couldn't it be cool to set its position (up or left, or ...) in the option menu?

Now I realize the true role of F5: loading a new fresh board.
I confusedly used it like a *reinit* command, cleaning everything on the same configured board (kind of *clear* command) when I lost the board during issue #61

**Comment by francoisschwarzentruber** [comment]
I try to fix the most as I can. This issue is not completely fixed. It should be more stable and more efficient.

1. ok
2. It is still very slow to update all computers. Also in case of network problem... it is not perfectly sure to your board back. I hope you will not have too many troubles. Otherwise, just share your screen with the tool you use for discussing with the students.
3. ok
4. ok! :)
5. Yes, that is a nice idea. But it will complicate a bit the interface.
6. Yes.

Other demand. I agree that the toolbar placement should be customizable.

Yes. F5: reload tableaunoir completely:
- if the board is not shared: it wil erase everything
- if the board is shared, it reloads the current shared board

Have a nice course!

**Comment by philardine** [comment]
Well, I am sorry: I couldn't try tableaunoir with my students today, so I (we) have to wait next week to try it again in real context.
I could only make the good experience that when reloading (F5) the background image is still there.

**Comment by francoisschwarzentruber** [comment]
Hello,
do you mean you couln't try because you did not have the opportunity, or because it did not work?
Have a nice day!

**Comment by philardine** [comment]
I didn't have the opportunity :'-(

**Comment by philardine** [comment]
Hello François,
I could try the feature this week, and I am pleased to tell you that background images are visible for all users :-)

**Comment by francoisschwarzentruber** [comment]
Oh, thank you for the good news! Thus, I will close this issue.
