### ISSUE TITLE
Disappointed with "Save as image" feature

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#59]
Hi!
In the past (I think it was before the use of TypeScript) I used to get images (png) for my blackboards to share the whole part of the board with students once the session was over, and it worked like a charm.
This feature has momentarily disappeared, then reappeared (thank you !), but now it captures only the visible part of the board. Moreover the capture is polluted by some pixels from the color palette (?).

**Comment by francoisschwarzentruber** [comment]
Hello,
indeed, I was able to have that bug too... :( That is very annoying. It is due to the library html2canvas. Probably the version is different or I do not know. Anyway, I will try to fix that issue.

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
thank you again for having posted this issue. If you want you could check whether it works properly on tableaunoir.github.io?

PS: the issue was solved by giving "fake" width to some HTML elements, before calling html2canvas, and then restore the width of these HTML elements for continuing to be able to use the application.

**Comment by philardine** [comment]
I am not able to appreciate the true value of your subterfuge, but thank you, it works again like a charm :-)
