### ISSUE TITLE
Geometric shapes and the shift key

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#66]
Hi!
Thank you for the good geometric shape tool :-)

I observed that you implemented the possibility to make regular shapes (square and circle) by pressing the shift key, and that's nice. But I still have two suggestions.
- Don't you think it would be nice to add a shift possibility for making straight lines? One would then be able to draw forced horizontal or forced vertical lines.
- Shouldn't users be aware of this shift possibility by a few words in section « ? Help » for example ?

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

out of the context, "Geometric shapes and the shift key" sounds like the title of some tale ;). A story involving the geometric shapes that live in the countryside, and that found a magical object: the shift key. Well, let us forget that story...

I completely agree with your two suggestions. The issue is solved.
