### ISSUE TITLE
Switching out of full screen confuses tableaunoir

### ISSUE THREAD

**Issue by brabalan** [tableaunoir/tableaunoir#75]
Suppose I teach a class using tableaunoir in full screen with not toolbar. When I switch out of full screen, I see two ways tableaunoir can get confused:
- navigating left and right now longer corresponds to the dividers (smaller screen = travel less, which is understandable)
- exporting to png truncates the right part of the board (which I think is bad)

Exporting in full screen works, so I guess there is some internal state that is changed (current width) that is taken into account when exporting (multiplied by number of boards) which returns too small a value.

**Comment by francoisschwarzentruber** [comment]
Thank you for your message.
- _Comment on the navigation left and right._ Yes, indeed, the navigation left right corresponds to the width/2, where width is the visible width of the canvas and it depends on the window size. I agree with you it can be confusing. A solution could be to navigate and detect where the vertical bar is. But the issue is then that some people may dislike it. Another option is to add a navigation mode / button or something. To have another mode annoys me because of the KISS (keep it simple, stupid) principle. What would be suitable for you?
- _Bug in exporting to png_. That is a bad behavior, yes. Sorry for that. I do not see yet where the bug is. The export in png relies on the library html2canvas that I trust. The bug may be either in that library, or in some dimension computation. But all the dimension computations for the png export are independent from the window.

I will try to solve the second point.

**Comment by brabalan** [comment]
For navigation I do not think there is a good solution. And for the export, I will try it after my class this afternoon and will let you know if there is still a problem.
