### ISSUE TITLE
"Export as image" feature doesn't always capture the whole board

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#76]
Hello,
The "export as image" feature captures only from the current visible part of the board to its right end.
Try this:
1. split the board with split tool
1. write a big 1 to the left part, then a big 2 to the right part
1. move one time right with right arrow
1. split the new board with split tool
1. write a big 3 to the right part (there is soon 2 at left)
1. export the board to a png file --> it will contain visible 2 & 3
1. move one time to the left with left arrow
1. export the board to a png file --> it will contain visible 1 & 2 & 3

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
Thank you for your very detailed procedure to get the bug. I really appreciate having such kind of step-by-step recipe to reach the bug. I think it is solved now. Better check.
Have a nice day!

PS: This export in png is tricky because I rely on html2canvas and the output of that library depends on parameter that should not be important (typically the output of a whole HTMLElement A should not depend on its position in another HTMLElement B containing A, because B is not rendered at all!

**Comment by philardine** [comment]
Dear François,
It works like a charm, thank you!

Thank you for your kindness and for your (always very fast) corrections :-)
I will try, as far as possible, to elaborate pertinent subjects and simple procedures.
Cheers
