### ISSUE TITLE
Inform the user when the eraser will become big

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#77]

**Comment by philardine** [comment]
Hello François,

Precisely! I wanted to write something about the eraser size change :-)
Sometimes you need to erase precisely some stuff, and the eraser is or becomes undesirably too big.
Sometimes you need to erase quickly a lot of stuff and the eraser does not get thick enough quickly enough.
In fact, I have often been embarrassed by the inability to choose a suitable thickness for the eraser

It would be nice to configure the thickness on the fly, while pressing the control key for example.
1. I begin to erase some stuff
1. realize I want a thicker (or thinner) eraser: I press Ctrl key while erasing, this stops erasing and increases the size of the eraser if I move away from the point where I pressed the Ctrl key (or decrease it if I get closer to that point)
1. I release the Ctr key, and the rest of my action erases with the new thickness

And rather than letting the gesture decide if the eraser should be thin or thick, maybe use the Shift key to toggle between two predefined thickness?

What do you think?

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
yes! thank you for your message. But, I actually implemented another solution. 
- when you shake the cursor, the eraser increases its size.
- the color (orange then red) alerts you when the eraser will increase. If you do not want, just calm down.
Do you think it is usable? For me, it is ok.
I will think about your proposal, that allows a better control on the size of the eraser.

**Comment by philardine** [comment]
Dear François,
I've tried your solution. I understand there is now 4 levels. That's more useful than before: better info, better control and better choices in the thickness. It's already very good, and it's very nice to use.

However my students are using mouse (not stylus, poor of them!) and we often need to erase parts of words drawn into circles, or potatoes should I say (we draw hierarchical tree structures). We lack a thinner eraser than what was provided (I have to try the new eraser in this context).
On the other way, I understand that a very thin eraser is not necessarily useful for the rest of the community...

Finally, to be frankly nasty, I sometimes felt the need for an eraser to delete a continuous line by just clicking anywhere on the line... do you see what I mean? Perhaps this could compensate for the problem with undo/redo on shared blackboards?

Don't worry, I could live without these features :-)
And don't hesitate to tell me if I cross the line!

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

I think it is natural to use (but not sure). When you use a thin eraser, you are usually very slow, and precise, so the eraser is not shaked and keep being with the first tiny thin eraser. If you erase more, you instinctively shake the eraser because the surface to erase is bigger, so you the eraser goes into the second level, and so on.

OK, I see. Several options:
1. use the black chalk to erase (but if there is a background, that does not work properly)
2. add a very very thin first level for the eraser
3. implement the change of thickness with Ctrl, Shift, or with keys

Concerning, the deletion of a continuous line... yes I understand the need. This is part of a big debate Canvas / SVG. Tableaunoir is based on Canvas, so you are modifying a bitmap. It makes many things easier: handling magnets, erasing (that is really an eraser etc.), easy to add "chalk effect" or whatever. On the contrast, SVG is vectorial and implementing multi-user undo/redo would be easier with SVG. Also, erasing a line would be easier with SVG (but not impossible to implement with Canvas).

What is your opinion about Canvas VS. SVG?

**Comment by philardine** [comment]
Dear François,

You're right. All things considered, I like this smart feature, and its simple (the most simple in fact) use.
I just regret an initial very thin eraser that would allow us to work without the problematic deletion of continuous lines.

On the debate Canvas vs SVG, I don't have an expert opinion...
I understand that WBO uses SVG (https://github.com/lovasoa/whitebophir) and it seems quite mature. WBO does not implement the notion of magnet, which is really a strong point of Tableaunoir :-)

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,

great that you find it usable! I added a very thin eraser for the first one.
Concerning the debate Canvas vs SVG, I start a document here: https://github.com/tableaunoir/ideas-and-thoughts/blob/main/canvas-vs-svg.md It sums up the advantages and disadvantages. The main advantage of Canvas is: the implement of magnets is sooooo easy! But the multi-user undo/redo is a nightmare.

**Comment by philardine** [comment]
Thank you for the thin eraser, I think it's enough.
And cursor colors are very useful too.

**Comment by francoisschwarzentruber** [comment]
I am glad it is ok for you. :)
